name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from github to runner
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
            python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt