name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from github to runner
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
            python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Code test
        env:
          PYTHONPATH: ./src  # Add the src directory to PYTHONPATH
        run: pytest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from github to runner
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
            python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Project
        run: python setup.py sdist bdist_wheel

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-build
          path: dist/
      
      - name: Install and Test CLI Locally
        run: |
          pip install dist/simple_python_project-0.1.0-py3-none-any.whl
          simple-python
          
  